"""Prompts are classes; their bodies are files.

The class is what the design asks for — `version` keys the eval store, subclassing is how a team
extends a shipped prompt, and a prompt change is a reviewable diff. What lives in the class is the
*binding*; what lives in the `.md` is the prose.

Nothing is generated by this: the markdown is an input read at render time, versioned and blamed
like any other file. Three things follow. Prompt text stays editable by the people who write it,
who are frequently not Python programmers. Brace and backslash hazards in prompt bodies stop being
a syntax problem. And — the reason this is a security property rather than an ergonomic one — a
prompt change proposed by the improvement loop is *data*, not executable code entering the import
graph of the module that defines every binding.

Bodies resolve through `importlib.resources` rather than `__file__`, so a shipped prompt works from
a wheel and a subclass can point at its own file. Resolution happens at render time, not at class
definition, so importing a lifecycle module performs no IO.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path
from typing import Any, ClassVar, Generic, TypeVar

from ..llm.types import Message
from .context import ContextPackage

P = TypeVar("P")
S = TypeVar("S")


class BodyNotFound(Exception):
    """A prompt names a body file that does not exist. Caught by `doctor`, not at first run."""


@dataclass(frozen=True)
class Body:
    """A lazily-resolved prompt body. Holds a reference, not the text."""

    package: str
    resource: str
    path: Path | None = None

    @classmethod
    def from_file(cls, resource: str, *, package: str = "") -> Body:
        return cls(package=package, resource=resource)

    @classmethod
    def from_path(cls, path: str | Path) -> Body:
        return cls(package="", resource=str(path), path=Path(path))

    def resolve(self, default_package: str = "") -> str:
        package = self.package or default_package
        if self.path is not None:
            if not self.path.exists():
                raise BodyNotFound(f"prompt body {self.path} does not exist")
            return self.path.read_text()
        if package:
            try:
                return (resources.files(package) / self.resource).read_text()
            except (FileNotFoundError, ModuleNotFoundError, AttributeError) as e:
                raise BodyNotFound(f"prompt body {self.resource!r} not found in package {package!r}") from e
        candidate = Path(self.resource)
        if not candidate.exists():
            raise BodyNotFound(f"prompt body {self.resource} does not exist")
        return candidate.read_text()


@dataclass(frozen=True)
class Frontmatter:
    """Advisory input to a Python-declared binding, never an alternate configuration surface."""

    model: str = ""
    guardrails: tuple[str, ...] = ()
    skills: tuple[str, ...] = ()
    max_tool_turns: int = 0
    load: str = ""  # "always" exempts a skill from progressive disclosure
    raw: dict[str, Any] = field(default_factory=dict)


def parse_frontmatter(text: str) -> tuple[Frontmatter, str]:
    """Split YAML frontmatter from a body. Absent frontmatter is not an error."""
    if not text.startswith("---"):
        return Frontmatter(), text
    end = text.find("\n---", 3)
    if end == -1:
        return Frontmatter(), text
    raw_block = text[3:end].strip()
    body = text[end + 4 :].lstrip("\n")
    try:
        import yaml

        data = yaml.safe_load(raw_block) or {}
    except Exception:  # pragma: no cover - defensive
        return Frontmatter(), body
    if not isinstance(data, dict):
        return Frontmatter(), body

    def seq(key: str) -> tuple[str, ...]:
        value = data.get(key) or []
        return tuple(str(v) for v in value) if isinstance(value, list) else ()

    return (
        Frontmatter(
            model=str(data.get("model") or ""),
            guardrails=seq("guardrails"),
            skills=seq("skills"),
            max_tool_turns=int(data.get("max-tool-turns") or data.get("max_tool_turns") or 0),
            load=str(data.get("load") or ""),
            raw=data,
        ),
        body,
    )


class Prompt(Generic[P, S]):
    """A prompt. Subclass it, override `emphasis`, or replace `render` wholesale."""

    version: ClassVar[str] = "1"
    body: ClassVar[Body | None] = None
    output: ClassVar[type | None] = None
    emphasis: ClassVar[str] = ""
    exemplars: ClassVar[tuple[str, ...]] = ()

    def package(self) -> str:
        return type(self).__module__.rsplit(".", 1)[0]

    def body_text(self) -> str:
        if self.body is None:
            raise BodyNotFound(f"{type(self).__name__} declares no body")
        return self.body.resolve(self.package())

    def system(self, layers: PromptLayers | None = None) -> str:
        """Compose the system prompt.

        Order is guardrails, body, skills, contexts — a framework invariant, resolved here because
        this is the only place it can be guaranteed. Guardrails are inlined first and verbatim:
        their position is a security property, not a rendering preference.
        """
        parts: list[str] = []
        if layers is not None:
            parts.extend(layers.guardrail_texts())
        parts.append(self.body_text().strip())
        if self.emphasis:
            parts.append(f"## Emphasis for this team\n\n{self.emphasis.strip()}")
        for exemplar in self.exemplars:
            parts.append(f"## Example\n\n{exemplar.strip()}")
        if layers is not None:
            parts.extend(layers.trailing_texts())
        return "\n\n".join(p for p in parts if p)

    def render(self, params: P, package: ContextPackage) -> list[Message]:
        """Params and context become messages. Override for a different shape."""
        rendered = package.render()
        user = f"{self.user_text(params)}\n\n{rendered}" if rendered else self.user_text(params)
        return [Message(role="user", content=user)]

    def user_text(self, params: P) -> str:
        return str(params)


@dataclass
class PromptLayers:
    """The layers around a body: guardrails before, skills and contexts after."""

    guardrails: tuple[tuple[str, str], ...] = ()  # (name, text)
    skills: tuple[tuple[str, str], ...] = ()
    contexts: tuple[tuple[str, str], ...] = ()

    def guardrail_texts(self) -> list[str]:
        if not self.guardrails:
            return []
        blocks = [
            "<!-- Guardrails are inlined first, verbatim: their position is a security property "
            "and is not delegated to import merge order. -->"
        ]
        blocks += [f"<!-- guardrail: {name} -->\n{text.strip()}" for name, text in self.guardrails]
        return blocks

    def trailing_texts(self) -> list[str]:
        return [
            f"<!-- {kind}: {name} -->\n{text.strip()}"
            for kind, entries in (("skill", self.skills), ("context", self.contexts))
            for name, text in entries
        ]

    def plus(
        self,
        *,
        guardrails: tuple[tuple[str, str], ...] = (),
        skills: tuple[tuple[str, str], ...] = (),
        contexts: tuple[tuple[str, str], ...] = (),
    ) -> PromptLayers:
        """These layers with more appended — the shape a repository extending a shipped set wants.

        Appended, never replaced: a house guardrail lands after the framework's, so extending the
        set cannot quietly drop the baseline. Replacing wholesale stays possible by constructing a
        fresh `PromptLayers`, which is the visible, greppable spelling of that decision.
        """
        return PromptLayers(
            guardrails=self.guardrails + guardrails,
            skills=self.skills + skills,
            contexts=self.contexts + contexts,
        )

    def projection(self, body_name: str) -> list[str]:
        """The section-identity list the characterization corpus asserts on.

        The body sentinel sits at its real position, because the invariant being protected is
        where the body sits *relative to* the layers — and a projection over fragments alone
        cannot express that.
        """
        return [
            *[f"guardrail:{n}" for n, _ in self.guardrails],
            f"body:{body_name}",
            *[f"skill:{n}" for n, _ in self.skills],
            *[f"context:{n}" for n, _ in self.contexts],
        ]
