"""Prompts are classes; their bodies are files.

The class is what the design asks for — `version` keys the eval store, subclassing is how a team
extends a shipped prompt, and a prompt change is a reviewable diff. What lives in the class is the
*binding*; what lives in the `.md` is the prose.

Nothing is generated by this: the markdown is an input read at render time, versioned and blamed
like any other file. Three things follow. Prompt text stays editable by the people who write it,
who are frequently not Python programmers. Brace and backslash hazards in prompt bodies stop being
a syntax problem. And — the reason this is a security property rather than an ergonomic one — a
prompt change proposed by the improvement loop is *data*, not executable code entering the import
graph of the module that defines every binding.

Bodies resolve through `importlib.resources` rather than `__file__`, so a shipped prompt works from
a wheel and a subclass can point at its own file. Resolution happens at render time, not at class
definition, so importing a lifecycle module performs no IO.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path
from typing import Any, ClassVar, Generic, Protocol, TypeVar, runtime_checkable

from ..llm.types import Message
from .context import ContextPackage

P = TypeVar("P")
S = TypeVar("S")


class BodyNotFound(Exception):
    """A prompt names a body file that does not exist. Caught by `doctor`, not at first run."""


@dataclass(frozen=True)
class Body:
    """A lazily-resolved prompt body. Holds a reference, not the text."""

    package: str
    resource: str
    path: Path | None = None

    @classmethod
    def from_file(cls, resource: str, *, package: str = "") -> Body:
        return cls(package=package, resource=resource)

    @classmethod
    def from_path(cls, path: str | Path) -> Body:
        return cls(package="", resource=str(path), path=Path(path))

    def resolve(self, default_package: str = "") -> str:
        package = self.package or default_package
        if self.path is not None:
            if not self.path.exists():
                raise BodyNotFound(f"prompt body {self.path} does not exist")
            return self.path.read_text()
        if package:
            try:
                return (resources.files(package) / self.resource).read_text()
            except (FileNotFoundError, ModuleNotFoundError, AttributeError) as e:
                raise BodyNotFound(f"prompt body {self.resource!r} not found in package {package!r}") from e
        candidate = Path(self.resource)
        if not candidate.exists():
            raise BodyNotFound(f"prompt body {self.resource} does not exist")
        return candidate.read_text()


@dataclass(frozen=True)
class Frontmatter:
    """What a prompt file says about itself: an identity and a one-line description.

    It used to declare `model`, `provider`, `max_tool_turns`, a `github:` credit budget and an
    `enforce:` block, inherited from the compiler this project replaced. None of it was ever read —
    `parse_frontmatter` had seven callers and all seven discarded the parsed object — and the
    mismatch was visible in the type: this dataclass declared `model: str` while every shipped file
    carried `model: {default: ..., allow: [...]}`. A field nothing consumes cannot be wrong, which
    is how it stayed wrong.

    Those fields are gone rather than wired, and the distinction is the docstring's own: frontmatter
    is "advisory input to a Python-declared binding, never an alternate configuration surface". A
    prompt body is data — a non-programmer edits it, and a pack can ship one — so a body that could
    choose the model, raise a turn cap or set a credit budget would be exactly the surface that
    sentence refuses. Which model runs and how long it may run are decisions `lockstep.py` makes,
    in code, loaded from a trusted ref.

    What is left is what a prompt may honestly say about itself. `name` is its identity, which the
    projection and the eval corpus key on. `description` is one line for a human reading a list.
    Neither can change what a run does.
    """

    #: The prompt's identity, e.g. `security-reviewer`. Qualified by the body's directory to form
    #: the projection sentinel — `review/security-reviewer` — so a corpus and a composed prompt
    #: agree without anybody restating the name in Python.
    name: str = ""
    #: One line, for `show-prompt` and `ls`. Never sent to the model.
    description: str = ""
    #: Everything else the file carried, unread. Kept so a house prompt may annotate itself without
    #: this parser refusing, and so `doctor` can one day say "this key does nothing".
    raw: dict[str, Any] = field(default_factory=dict)


def parse_frontmatter(text: str) -> tuple[Frontmatter, str]:
    """Split YAML frontmatter from a body. Absent frontmatter is not an error."""
    if not text.startswith("---"):
        return Frontmatter(), text
    end = text.find("\n---", 3)
    if end == -1:
        return Frontmatter(), text
    raw_block = text[3:end].strip()
    body = text[end + 4 :].lstrip("\n")
    try:
        import yaml

        data = yaml.safe_load(raw_block) or {}
    except Exception:  # pragma: no cover - defensive
        return Frontmatter(), body
    if not isinstance(data, dict):
        return Frontmatter(), body

    return (
        Frontmatter(
            name=str(data.get("name") or ""),
            description=str(data.get("description") or ""),
            raw=data,
        ),
        body,
    )


class Prompt(Generic[P, S]):
    """A prompt. Subclass it, override `emphasis`, or replace `render` wholesale."""

    version: ClassVar[str] = "1"
    body: ClassVar[Body | None] = None
    output: ClassVar[type | None] = None
    emphasis: ClassVar[str] = ""
    exemplars: ClassVar[tuple[str, ...]] = ()
    #: The `body:` sentinel this prompt contributes to a projection. Declared only where the name
    #: differs from the resource — the four review lenses, whose bodies are `review/security.md`
    #: and whose corpus identity is `review/security-reviewer`. Left empty everywhere else, where
    #: `body_label` derives it, so a house prompt gets a stable identity without being told to
    #: invent a convention.
    body_name: ClassVar[str] = ""

    def __init_subclass__(cls, **kwargs: Any) -> None:
        """Refuse a body that is a string rather than a `Body`.

        `body_text` calls `self.body.resolve(...)`, so a plain string produces
        `AttributeError: 'str' object has no attribute 'resolve'` — at render time, from inside the
        composer, naming neither the prompt nor the fix. `docs/cookbook.md` recipe 9 shipped
        exactly that mistake and the docs test did not catch it, because executing a snippet proves
        the class defines, not that the prompt it defines can render.

        A string body is also the reasonable guess: every other field on this class takes one. So
        this is a refusal at class creation naming the two constructors, rather than an
        AttributeError three layers down at the moment somebody is trying to review a change.
        """
        super().__init_subclass__(**kwargs)
        if isinstance(cls.body, str):
            raise TypeError(
                f"{cls.__name__}.body is a string. A prompt body is a file, not a literal — "
                f"prompt text is data a non-programmer edits and a diff can review, which is the "
                f"reason it lives outside the module. Use:\n\n"
                f"    body = Body.from_path('.lockstep/prompts/{cls.__name__.lower()}.md')\n\n"
                f"or, for a body shipped inside a package:\n\n"
                f"    body = Body.from_file('review/security.md', package='your_pack')\n"
            )

    def package(self) -> str:
        return type(self).__module__.rsplit(".", 1)[0]

    def meta(self) -> Frontmatter:
        """What the body file says about itself. Empty when there is no body or no header."""
        if self.body is None:
            return Frontmatter()
        try:
            front, _ = parse_frontmatter(self.body.resolve(self.package()))
        except BodyNotFound:
            return Frontmatter()
        return front

    def describe(self) -> str:
        """One line for a human reading a list of prompts. Never sent to the model."""
        return self.meta().description

    def body_label(self) -> str:
        """What this prompt is called in a projection.

        Read from the body file's own `name`, qualified by the directory the body sits in, so
        `review/security.md` declaring `name: security-reviewer` is `review/security-reviewer` —
        which is what the characterization corpus has always keyed on.

        That used to be four `body_name` ClassVars restating in Python what the four files already
        said. Two spellings of one fact is one of them going stale, and the Python copy is the one
        a prompt author would never think to update.

        Falls back to the resource path for a body with no header, and to the class name for a
        `render`-replacing subclass with no body at all. `body_name` still wins when set, because a
        house prompt may need a label its file does not carry.
        """
        if self.body_name:
            return self.body_name
        if self.body is None:
            return type(self).__name__
        resource = self.body.resource
        stem = resource[:-3] if resource.endswith(".md") else resource
        declared = self.meta().name
        if not declared:
            return stem
        directory = stem.rsplit("/", 1)[0] if "/" in stem else ""
        return f"{directory}/{declared}" if directory else declared

    def body_text(self) -> str:
        """The body, with its frontmatter stripped.

        Stripped, because it was being sent to the model. Every shipped body opens with a YAML
        header — `name`, `description`, `model`, `provider`, `max-ai-credits`, a `github:` block —
        and `Frontmatter` is documented as "advisory input to a Python-declared binding, never an
        alternate configuration surface". Advisory turned out to mean unread: `parse_frontmatter`
        is called at seven sites and every one discards the parsed object, so nothing anywhere
        consumes those keys.

        The header still reached the model, though, because this method did not strip it — roughly
        2.6KB of dead compiler-era configuration at the top of every review's system prompt, in the
        position where instructions carry the most weight, telling the model things like
        `model: { default: claude-sonnet-4-6 }`. The guardrail and skill fragments were already
        stripped by `prompts/review.py::_text`; only the body was not, which is why nobody noticed.

        Found by a review that asked what the framework actually sends, on a framework whose whole
        claim is that it standardises exactly that.
        """
        if self.body is None:
            raise BodyNotFound(f"{type(self).__name__} declares no body")
        _, body = parse_frontmatter(self.body.resolve(self.package()))
        return body

    def system(self, layers: PromptLayers | None = None) -> str:
        """Compose the system prompt.

        Order is guardrails, body, skills, contexts — a framework invariant, resolved here because
        this is the only place it can be guaranteed. Guardrails are inlined first and verbatim:
        their position is a security property, not a rendering preference.
        """
        parts: list[str] = []
        if layers is not None:
            parts.extend(layers.guardrail_texts())
        parts.append(self.body_text().strip())
        if self.emphasis:
            parts.append(f"## Emphasis for this team\n\n{self.emphasis.strip()}")
        for exemplar in self.exemplars:
            parts.append(f"## Example\n\n{exemplar.strip()}")
        if layers is not None:
            parts.extend(layers.trailing_texts())
        return "\n\n".join(p for p in parts if p)

    def render(self, params: P, package: ContextPackage) -> list[Message]:
        """Params and context become messages. Override for a different shape."""
        rendered = package.render()
        user = f"{self.user_text(params)}\n\n{rendered}" if rendered else self.user_text(params)
        return [Message(role="user", content=user)]

    def user_text(self, params: P) -> str:
        return str(params)


@dataclass
class PromptLayers:
    """The layers around a body: guardrails before, skills and contexts after."""

    guardrails: tuple[tuple[str, str], ...] = ()  # (name, text)
    skills: tuple[tuple[str, str], ...] = ()
    contexts: tuple[tuple[str, str], ...] = ()

    def guardrail_texts(self) -> list[str]:
        if not self.guardrails:
            return []
        blocks = [
            "<!-- Guardrails are inlined first, verbatim: their position is a security property "
            "and is not delegated to import merge order. -->"
        ]
        blocks += [f"<!-- guardrail: {name} -->\n{text.strip()}" for name, text in self.guardrails]
        return blocks

    def trailing_texts(self) -> list[str]:
        return [
            f"<!-- {kind}: {name} -->\n{text.strip()}"
            for kind, entries in (("skill", self.skills), ("context", self.contexts))
            for name, text in entries
        ]

    def plus(
        self,
        *,
        guardrails: tuple[tuple[str, str], ...] = (),
        skills: tuple[tuple[str, str], ...] = (),
        contexts: tuple[tuple[str, str], ...] = (),
    ) -> PromptLayers:
        """These layers with more appended — the shape a repository extending a shipped set wants.

        Appended, never replaced: a house guardrail lands after the framework's, so extending the
        set cannot quietly drop the baseline. Replacing wholesale stays possible by constructing a
        fresh `PromptLayers`, which is the visible, greppable spelling of that decision.
        """
        return PromptLayers(
            guardrails=self.guardrails + guardrails,
            skills=self.skills + skills,
            contexts=self.contexts + contexts,
        )

    def projection(self, body_name: str) -> list[str]:
        """The section-identity list the characterization corpus asserts on.

        The body sentinel sits at its real position, because the invariant being protected is
        where the body sits *relative to* the layers — and a projection over fragments alone
        cannot express that.
        """
        return [
            *[f"guardrail:{n}" for n, _ in self.guardrails],
            f"body:{body_name}",
            *[f"skill:{n}" for n, _ in self.skills],
            *[f"context:{n}" for n, _ in self.contexts],
        ]


@dataclass(frozen=True)
class Composition:
    """One inspectable prompt: what a bound adapter would compose under a name.

    `show-prompt` used to import the shipped maps directly, so every override `docs/extending.md`
    tells a team to write was invisible to the one command whose job is answering "what was the
    model actually told". The fix cannot be the CLI reaching into six adapters and knowing which
    attribute each keeps its map in — that is inference, and this framework declares. So an
    adapter says what it composes, and this is what it says it with.
    """

    label: str
    prompt: Prompt[Any, Any]
    layers: PromptLayers
    #: The class that owns this composition — `AiReview`, `TDD` — or `"shipped"` when nothing is
    #: bound and the answer came from the framework's own map.
    source: str

    def projection(self) -> list[str]:
        return self.layers.projection(self.prompt.body_label())

    def text(self) -> str:
        return self.prompt.system(self.layers)


def compositions(
    prompts: Mapping[str, type[Prompt[Any, Any]]],
    layers: PromptLayers,
    *,
    verb: str,
    source: str,
) -> dict[str, Composition]:
    """Label an adapter's prompt map for inspection.

    Keys arrive already namespaced everywhere except the review lenses, which are addressed by
    bare aspect (`security`) because that is what `--aspect` takes. Both spellings resolve; the
    label is the qualified one, so two verbs may hold a prompt of the same name.
    """
    return {
        label: Composition(label=label, prompt=cls(), layers=layers, source=source)
        for label, cls in ((key if "/" in key else f"{verb}/{key}", cls) for key, cls in prompts.items())
    }


@runtime_checkable
class Inspectable(Protocol):
    """What `show-prompt` and `ls` ask a bound adapter for.

    A protocol rather than a base class, because the AI adapters share no ancestor — `AiReview` is
    not an `AiStrategy` — and because an adapter somebody else writes should be inspectable by
    satisfying an interface rather than by inheriting from us.
    """

    def compositions(self) -> dict[str, Composition]: ...
