"""Shared emission state: resolved pins, provenance, and the generated-file registry."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .. import __version__
from ..errors import EmitError
from ..spec.model import Command, Profile, SourceFile, Spec

PINS_PATH = ".pipeline/pins.lock"
DEFAULT_ACTIONS_REPO = "pipeline-fw/pipeline-actions"
DEFAULT_EXEC_IMAGE = "ghcr.io/pipeline-fw/exec"


@dataclass
class Pins:
    """Resolved capability pins: tags/versions from the manifest, SHAs/digests from pins.lock."""

    actions_repo: str = DEFAULT_ACTIONS_REPO
    actions_tag: str = ""
    actions_sha: str = ""
    exec_package: str = "pipeline-exec"
    exec_version: str = ""
    exec_image: str = DEFAULT_EXEC_IMAGE
    exec_digest: str = ""
    gh_aw_version: str = ""
    external: dict[str, str] = field(default_factory=dict)
    external_tags: dict[str, str] = field(default_factory=dict)
    resolved: bool = False

    @classmethod
    def load(cls, root: Path, spec: Spec) -> Pins:
        caps = spec.manifest.capabilities
        actions_repo, _, actions_tag = caps.actions.partition("@")
        actions_repo = actions_repo.removeprefix("github.com/") or DEFAULT_ACTIONS_REPO
        exec_package, _, exec_version = caps.exec.partition("==")

        pins = cls(
            actions_repo=actions_repo,
            actions_tag=actions_tag,
            exec_package=exec_package or "pipeline-exec",
            exec_version=exec_version,
            gh_aw_version=caps.gh_aw,
        )

        path = root / PINS_PATH
        if not path.is_file():
            return pins

        data: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
        cap_pins = data.get("capabilities", {}) or {}
        actions = cap_pins.get("actions", {}) or {}
        exec_pin = cap_pins.get("exec", {}) or {}
        pins.actions_repo = str(actions.get("repo") or pins.actions_repo)
        pins.actions_tag = str(actions.get("tag") or pins.actions_tag)
        pins.actions_sha = str(actions.get("sha") or "")
        pins.exec_image = str(exec_pin.get("image") or DEFAULT_EXEC_IMAGE)
        pins.exec_digest = str(exec_pin.get("digest") or "")
        pins.exec_version = str(exec_pin.get("version") or pins.exec_version)
        pins.external = {str(k): str(v.get("sha", "")) for k, v in (data.get("external") or {}).items()}
        pins.external_tags = {
            str(v.get("sha", "")): str(v.get("tag", "")) for v in (data.get("external") or {}).values()
        }
        pins.resolved = bool(pins.actions_sha)
        return pins

    def action(self, name: str) -> str:
        """A pinned reference to one of the capability repo's composite actions."""
        if not self.actions_sha:
            raise EmitError(
                f"capability action {name!r} is not pinned",
                hint=f"run `lockstep pin` to resolve {self.actions_repo}@{self.actions_tag} into {PINS_PATH}",
            )
        return f"{self.actions_repo}/{name}@{self.actions_sha}"

    def external_action(self, name: str) -> str:
        sha = self.external.get(name)
        if not sha:
            raise EmitError(
                f"external action {name!r} is not pinned",
                hint=f"add it to the `external` block of {PINS_PATH}",
            )
        return f"{name}@{sha}"

    def exec_container(self) -> str:
        if not self.exec_digest:
            raise EmitError(
                "executor image is not pinned by digest",
                hint=f"add capabilities.exec.digest to {PINS_PATH}",
            )
        return f"{self.exec_image}@{self.exec_digest}"

    def sha_tags(self) -> dict[str, str]:
        """sha -> human tag, used to annotate `uses:` lines with the version they pin."""
        tags = dict(self.external_tags)
        if self.actions_sha and self.actions_tag:
            tags[self.actions_sha] = self.actions_tag
        return {k: v for k, v in tags.items() if k and v}


@dataclass
class EmitContext:
    """Everything an emitter needs, plus the provenance it must record."""

    spec: Spec
    pins: Pins
    profile: Profile
    multi_profile: bool = False
    runs_on_override: str = ""

    @property
    def runs_on(self) -> str:
        return self.runs_on_override or self.spec.manifest.target.default_runs_on

    @property
    def state_db_path(self) -> str:
        return f"{self.output_dir_env}/.state/{self.spec.manifest.name}.db"

    @property
    def out_dir(self) -> str:
        return self.spec.manifest.target.out

    @property
    def output_dir_env(self) -> str:
        return "outputs"

    def header(self, sources: list[SourceFile | None], *, extra: list[str] | None = None) -> list[str]:
        """The provenance block every generated file carries."""
        stamps = [s.stamp() for s in sources if s is not None]
        lines = [
            f"GENERATED by lockstep {__version__} — do not edit.",
            "Edit the spec, add an overlay, or run `lockstep eject` on this file.",
            f"sources: {' '.join(stamps)}" if stamps else "sources: (none)",
        ]
        if self.profile.name:
            lines.append(f"profile: {self.profile.name}")
        lines.extend(extra or [])
        return lines

    def resolved_values(self) -> dict[str, str]:
        """Profile values with `${NAME}` references lowered to secret/var expressions."""
        from .profiles import resolve_value

        location = self.profile.src.rel if self.profile.src else self.profile.name
        return {
            key: resolve_value(raw, self.profile, location=location)
            for key, raw in self.profile.values.items()
        }

    def expand(self, text: str, command: Command | None = None) -> str:
        """Resolve `{param}`, `{profile_value}`, `{output_dir}` and `{pipeline_name}` placeholders.

        Command parameters win over profile values: a command that declares `profile` as a
        parameter means the caller chooses it, and the compiled workflow must read its input.
        """
        if command:
            chat = command.github.command
            from_comment = set(chat.arguments) if chat else set()
            for parameter in command.parameters:
                reference = "${{ inputs." + parameter.input_name + " }}"
                if parameter.name in from_comment:
                    # The same pipeline is reachable two ways. A dispatch supplies inputs; a comment
                    # supplies the same values through the gate, and a step should not care which.
                    reference = (
                        "${{ inputs."
                        + parameter.input_name
                        + " || needs.command-gate.outputs."
                        + parameter.input_name
                        + " }}"
                    )
                text = text.replace("{" + parameter.name + "}", reference)
            if chat:
                # What the human actually wrote after the command — usually the point of the run.
                text = text.replace("{instruction}", "${{ needs.command-gate.outputs.instruction }}")
                text = text.replace("{pull_request}", "${{ needs.command-gate.outputs.pull_request }}")
                # The bare words after the command, as a JSON array — what a pipeline fans out over
                # when one invocation asks for several things at once.
                text = text.replace("{positional}", "${{ needs.command-gate.outputs.positional }}")
        for key, value in self.resolved_values().items():
            text = text.replace("{" + key + "}", value)
        text = text.replace("{output_dir}", self.output_dir_env)
        text = text.replace("{state_db}", self.state_db_path)
        return text.replace("{pipeline_name}", self.spec.manifest.name)
